FROM mysql:8.0

# Définir des variables d'environnement par défaut
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=carpart_clients
ENV MYSQL_ROOT_HOST=%

COPY init.sql /docker-entrypoint-initdb.d/
EXPOSE 3306
VOLUME /var/lib/mysql